script: "git submodule update --init && bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby
  - rbx-18mode
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - carlos@plataformatec.com.br
    - rafael.franca@plataformatec.com.br
